# Generated by Django 5.0.2 on 2024-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingmodel',
            name='waitingTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
