# Generated by Django 5.0.4 on 2024-06-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(unique=True)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('gamesWon', models.IntegerField(default=0)),
                ('gamesLost', models.IntegerField(default=0)),
                ('gamesPlayed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.IntegerField(choices=[(0, 'Playground'), (1, 'Cornfield'), (2, 'Dorm')], default='Playground')),
                ('ball', models.IntegerField(choices=[(0, 'Gold'), (1, 'Silver'), (2, 'Diamond')], default=1)),
                ('paddle', models.IntegerField(choices=[(0, 'Guard A'), (1, 'Guard B'), (2, 'Player A'), (3, 'Player B'), (4, 'Boss')], default=3)),
                ('table', models.IntegerField(choices=[(0, 'Metal'), (1, 'Concrete'), (2, 'Wooden')], default=1)),
                ('score', models.IntegerField(choices=[(7, '7'), (11, '11'), (17, '17')], default=7)),
                ('powerups', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pongapp.gameuser')),
            ],
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Not_Started'), (1, 'Playing'), (2, 'Finished')], default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1', to='pongapp.gameuser')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player2', to='pongapp.gameuser')),
            ],
        ),
    ]
