# Generated by Django 5.0.4 on 2024-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='scene',
            field=models.IntegerField(choices=[(0, 'Playground'), (1, 'Cornfield'), (2, 'Dorm'), (3, 'OpenWorld')], default=3),
        ),
    ]
