# Generated by Django 5.0.4 on 2024-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='table',
            field=models.IntegerField(choices=[(0, 'Metal'), (1, 'Concrete'), (2, 'Wooden')], default=2),
        ),
    ]
