# Generated by Django 5.0.4 on 2024-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongapp', '0002_alter_gamesettings_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematch',
            name='date',
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='status',
            field=models.IntegerField(choices=[(0, 'Playing'), (1, 'Finished')], default=0),
        ),
    ]
