FROM nginx:latest

COPY /conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY /tools/index.html /usr/share/nginx/html
COPY /tools/style.css /usr/share/nginx/html
COPY /tools/script.js /usr/share/nginx/html
