## Field dimensions

FIELD_WIDTH = 400
FIELD_HEIGHT = 200

## Ball initial values

BALL_POSITION_X = 0
BALL_POSITION_Y = 0
BALL_DIR_X = 1
BALL_DIR_Y = 1
BALL_SPEED = 2

## Paddle1 initial values

PADDLE1_WIDTH = 10
PADDLE1_HEIGHT = 30
PADDLE1_POSITION_X = -FIELD_WIDTH / 2 + PADDLE1_WIDTH
PADDLE1_DIR_Y = 0
PADDLE1_SPEED = 5
PADDLE1_SCORE = 0

## Paddle2 initial values

PADDLE2_WIDTH = 10
PADDLE2_HEIGHT = 30
PADDLE2_POSITION_X = FIELD_WIDTH / 2 - PADDLE2_WIDTH
PADDLE2_DIR_Y = 0
PADDLE2_SPEED = 5
PADDLE2_SCORE = 0

## Party settings

SMALL_LIMIT_SCORE = 7
MID_LIMIT_SCORE = 11
LONG_LIMIT_SCORE = 21
